org: osvaldobazzanbini
service: stockflowback

provider:
  name: aws
  runtime: nodejs20.x
  architecture: arm64

package:
  individually: true
  patterns:
    - '!**.spec.ts'

build:
  esbuild:
    bundle: true
    minify: true
    exclude: 
      - '@aws-sdk/*'

functions:
  hello:
    handler: src/functions/products/create-product/handler.handler
    events:
      - httpApi:
          path: /
          method: post
